# Generated by Django 5.1.2 on 2024-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_alter_evento_dentista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
