# Generated by Django 5.1.2 on 2024-11-28 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0005_cliente_delete_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dentes_com_circulo', models.JSONField(default=list)),
                ('dentes_com_risco', models.JSONField(default=list)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='consultorio.cliente')),
            ],
        ),
    ]
