# Generated by Django 5.1.2 on 2024-12-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0007_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('finalizado', models.BooleanField(default=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField()),
                ('data_finalizado', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='anaminesia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='datas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='consultorio.cliente'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='procedimentos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='consultorio.procedimento'),
        ),
    ]
