# Generated by Django 5.1.2 on 2024-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0009_alter_orcamento_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='data_finalizado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
