# Generated by Django 5.1.2 on 2024-12-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0010_alter_procedimento_data_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='procedimentos',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, related_name='orcamentos', to='consultorio.procedimento'),
        ),
    ]
