# Generated by Django 5.1.2 on 2025-01-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0011_remove_orcamento_procedimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='dentes_com_circulo_nao_preenchido',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='dentes_com_x',
            field=models.JSONField(default=list),
        ),
    ]
