# Generated by Django 5.1.2 on 2025-01-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0012_orcamento_dentes_com_circulo_nao_preenchido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='evento',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='consultorio.cliente'),
        ),
        migrations.AddField(
            model_name='evento',
            name='protetico',
            field=models.BooleanField(default=False),
        ),
    ]
