# Generated by Django 5.1.2 on 2025-01-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0014_rename_cliente_evento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='consultorio.cliente'),
        ),
    ]
